In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. Visualization

In [3]:
df = pd.read_csv("./input/Womens Clothing E-Commerce Reviews.csv")

In [4]:
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [5]:
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing / len(df)).round(3)
mv = pd.concat([missing, missing_pct], axis=1)
mv.columns = ["missing_count", "missing_ratio"]
print("\nMissing values:\n", mv[mv.missing_count > 0])

Missing values:
                  missing_count  missing_ratio
Title                     3810          0.162
Review Text                845          0.036
Department Name             14          0.001
Class Name                  14          0.001
Division Name               14          0.001

In [6]:
num_df = df.select_dtypes(include=[np.number])
if not num_df.empty:
    corr = num_df.corr(numeric_only=True)
    print("\nTop correlations:")
    print(
        corr.abs()
            .where(~np.eye(len(corr), dtype=bool))
            .stack()
            .sort_values(ascending=False)
            .head(10)
    )

Top correlations:
Recommended IND          Rating                     0.792336
Rating                   Recommended IND            0.792336
Positive Feedback Count  Recommended IND            0.069045
Recommended IND          Positive Feedback Count    0.069045
Rating                   Positive Feedback Count    0.064961
Positive Feedback Count  Rating                     0.064961
Clothing ID              Positive Feedback Count    0.046356
Positive Feedback Count  Clothing ID                0.046356
Age                      Positive Feedback Count    0.043079
Positive Feedback Count  Age                        0.043079
dtype: float64

# 2. Data Preparation

In [7]:
texts = df["Review Text"].astype(str)

In [8]:
import re
import unicodedata

def normalize_text(text):
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_text"] = texts.apply(normalize_text)

In [9]:
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,clean_text
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,absolutely wonderful - silky and sexy and comf...
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,love this dress! it's sooo pretty. i happened ...
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,i had such high hopes for this dress and reall...
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"i love, love, love this jumpsuit. it's fun, fl..."
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,this shirt is very flattering to all due to th...

In [10]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
from nltk.tokenize import word_tokenize

df["tokens"] = df["clean_text"].apply(word_tokenize)

[nltk_data] Downloading package punkt to /home/alexander/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/alexander/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

# tokens -> strings (if needed)
texts = df["tokens"].apply(lambda x: " ".join(x))

vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2)
)

X = vectorizer.fit_transform(texts)
y = df["Recommended IND"]

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [13]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(
    max_iter=1000,
    n_jobs=-1
)

clf.fit(X_train, y_train)

/home/alexander/Work/python/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

LogisticRegression(max_iter=1000, n_jobs=-1)

In [14]:
from sklearn.metrics import classification_report

y_pred = clf.predict(X_val)
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.54      0.65       835
           1       0.91      0.97      0.94      3863

    accuracy                           0.90      4698
   macro avg       0.86      0.76      0.79      4698
weighted avg       0.89      0.90      0.89      4698

In [15]:
import torch
from torch.utils.data import Dataset

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [43]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("google/bert_uncased_L-2_H-128_A-2")
encodings = tokenizer(
    df["clean_text"].tolist(),
    truncation=True,
    padding=True,
    return_tensors="pt"
)

config.json:   0%|          | 0.00/382 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

In [44]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "google/bert_uncased_L-2_H-128_A-2",
    num_labels=df["Recommended IND"].nunique()
)

model.safetensors:   0%|          | 0.00/17.7M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google/bert_uncased_L-2_H-128_A-2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [45]:
encodings["labels"] = y.tolist()
dataset = TextDataset(encodings, y.tolist())

In [46]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
model = model.to(device)

Using device: cuda

In [47]:
from torch.utils.data import random_split
train_dataset, test_dataset = random_split(
    dataset,
    [0.8, 0.2],
    generator=torch.Generator().manual_seed(42)  # reproducibility
)

In [48]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    fp16=torch.cuda.is_available(),
    dataloader_pin_memory=torch.cuda.is_available()
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)
torch.cuda.empty_cache()
trainer.train()

TrainOutput(global_step=3525, training_loss=0.33160648751766125, metrics={'train_runtime': 361.1469, 'train_samples_per_second': 156.078, 'train_steps_per_second': 9.761, 'total_flos': 22658972584680.0, 'train_loss': 0.33160648751766125, 'epoch': 3.0})

In [49]:
trainer.evaluate()

{'eval_loss': 0.29566067457199097,
 'eval_runtime': 7.7633,
 'eval_samples_per_second': 605.025,
 'eval_steps_per_second': 37.87,
 'epoch': 3.0}